const Customers = [
  {
    customerName: "Ron Cooper",
    company: "Microsdssoft",
    phoneNumber: "(215) 333-0118",
    mail: "jane@microsoft.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Ronald Richards",
    company: "Adobe",
    phoneNumber: "(225) 555-6532",
    mail: "jane@microsoft.com",
    country: "United States",
    status: "Inactive",
  },
  {
    customerName: "Marvin McKinney",
    company: "Tesla",
    phoneNumber: "(225) 112-3233",
    mail: "jane@microsoft.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Jane Cooper",
    company: "Microsdssoft",
    phoneNumber: "(225) 555-0118",
    mail: "marvin@tesla.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Jane Cooper",
    company: "Microsdssoft",
    phoneNumber: "(215) 555-0118",
    mail: "kathryn@microsoft.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Kristin Watson",
    company: "Microsdssoft",
    phoneNumber: "(344) 555-3321",
    mail: "jane@microsoft.com",
    country: "United States",
    status: "Inactive",
  },
  {
    customerName: "Jane Cooper",
    company: "Yahoo",
    phoneNumber: "(225) 555-0118",
    mail: "jane@microsoft.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Jane Cooper",
    company: "Microsdssoft",
    phoneNumber: "(225) 555-0118",
    mail: "kristin@facebook.com",
    country: "United States",
    status: "Inactive",
  },
];
